-- Moon data
INSERT INTO moon (name, planet_id, year_discovered, description) VALUES
('Io', 2, 1610, 'The innermost of the four Galilean moons of Jupiter'),
('Europa', 3, 1610, 'The smallest of the four Galilean moons of Jupiter'),
('Ganymede',4, 1610, 'The largest moon in the Solar System'),
('Callisto', 5, 1610, 'The second-largest moon in the Solar System'),
('Titan', 6, 1655, 'The largest moon of Saturn'),
('Triton', 7, 1846, 'The largest natural satellite of Neptune'),
('Rhea', 5, 1672, 'The second-largest moon of Saturn'),
('Iapetus', 5, 1671, 'A moon of Saturn'),
('Dione', 5, 1684, 'A moon of Saturn'),
('Enceladus', 5, 1789, 'A moon of Saturn'),
('Mimas', 5, 1789, 'A moon of Saturn'),
('Hyperion', 5, 1848, 'A moon of Saturn'),
('Ariel', 7, 1851, 'A moon of Uranus'),
('Umbriel', 7, 1851, 'A moon of Uranus'),
('Titania', 7, 1787, 'The largest moon of Uranus'),
('Oberon', 7, 1787, 'The second-largest moon of Uranus'),
('Miranda', 7, 1948, 'A moon of Uranus'),
('Triton2', 8, 1846, 'The largest natural satellite of Neptune'),
('Nereid', 8, 1949, 'A moon of Neptune'),
('Proteus', 8, 1989, 'A moon of Neptune'),
('Larissa', 8, 1981, 'A moon of Neptune'),
('Galatea', 8, 1989, 'A moon of Neptune'),
('Despina', 8, 1989, 'A moon of Neptune'),
('Thalassa', 8, 1989, 'A moon of Neptune'),
('Naiad', 8, 1989, 'A moon of Neptune'),
('Charon', 9, 1978, 'The largest moon of Pluto'),
('Styx', 9, 2012, 'A moon of Pluto'),
('Nix', 9, 2005, 'A moon of Pluto'),
('Kerberos', 9, 2011, 'A moon of Pluto'),
('Hydra', 9, 2005, 'A moon of Pluto');